"""
Django settings for ecommerce_core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+((g5b#k2&2+r*cgjofknr8c3&rz)=h36ns97wqkw$hnf3hbep'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',

    # Local apps
    'apps.user_service',
    'apps.product_service',
    'apps.order_service',
    'apps.payment_service',
    'apps.shipping_service',
    'apps.recommendation_service',
    'apps.analytic_service',
    'apps.admin_service',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles'),
]

ROOT_URLCONF = 'ecommerce_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'user_service_db',
        'USER': 'user_service_user',
        'PASSWORD': 'user_service_password',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'product_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'product_service_db',
        'USER': 'product_service_user',
        'PASSWORD': 'product_service_password',
        'HOST': 'localhost',
        'PORT': '5433',
    },
    'order_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'order_service_db',
        'USER': 'order_service_user',
        'PASSWORD': 'order_service_password',
        'HOST': 'localhost',
        'PORT': '5434',
    },
    'payment_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'payment_service_db',
        'USER': 'payment_service_user',
        'PASSWORD': 'payment_service_password',
        'HOST': 'localhost',
        'PORT': '5435',
    },
    'shipping_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'shipping_service_db',
        'USER': 'shipping_service_user',
        'PASSWORD': 'shipping_service_password',
        'HOST': 'localhost',
        'PORT': '5436',
    },
    'recommendation_db': {
        'ENGINE': 'djongo',
        'NAME': 'recommendation_service_db',
        'CLIENT': {
            'host': 'mongodb://recommendation_service_user:recommendation_service_password@localhost:27017/recommendation_service_db',
            'authSource': 'admin',
        }
    },
    'analytic_db': {
        'ENGINE': 'djongo',
        'NAME': 'analytic_service_db',
        'CLIENT': {
            'host': 'mongodb://analytic_service_user:analytic_service_password@localhost:27018/analytic_service_db',
            'authSource': 'admin',
        }
    },
    'admin_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'admin_service_db',
        'USER': 'admin_service_user',
        'PASSWORD': 'admin_service_password',
        'HOST': 'localhost',
        'PORT': '5437',
    },
}

DATABASE_ROUTERS = [
    'ecommerce_core.routers.UserServiceRouter',
    'ecommerce_core.routers.ProductServiceRouter',
    'ecommerce_core.routers.OrderServiceRouter',
    'ecommerce_core.routers.PaymentServiceRouter',
    'ecommerce_core.routers.ShippingServiceRouter',
    'ecommerce_core.routers.RecommendationServiceRouter',
    'ecommerce_core.routers.AnalyticServiceRouter',
    'ecommerce_core.routers.AdminServiceRouter',
]

# Cấu hình Redis cache (tùy chọn)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Sử dụng Redis cho session (tùy chọn)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = 'user_service.User'
