# Generated by Django 5.2 on 2025-04-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('value', models.FloatField()),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aggregated_statistics',
                'indexes': [models.Index(fields=['metric_name'], name='aggregated__metric__2e482a_idx'), models.Index(fields=['period_start'], name='aggregated__period__5794ac_idx')],
                'unique_together': {('metric_name', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('period', models.CharField(max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('unique_views', models.IntegerField(default=0)),
                ('cart_adds', models.IntegerField(default=0)),
                ('purchases', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('conversion_rate', models.FloatField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_performance',
                'indexes': [models.Index(fields=['product_id'], name='product_per_product_341099_idx'), models.Index(fields=['period_start'], name='product_per_period__a14202_idx')],
                'unique_together': {('product_id', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('results_count', models.IntegerField()),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('clicked_products', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_queries',
                'indexes': [models.Index(fields=['query_text'], name='search_quer_query_t_f8c040_idx'), models.Index(fields=['timestamp'], name='search_quer_timesta_7fd56f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SellerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField()),
                ('period', models.CharField(max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sales', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('product_performance', models.JSONField(default=dict)),
                ('average_rating', models.FloatField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seller_analytics',
                'indexes': [models.Index(fields=['seller_id'], name='seller_anal_seller__0cd13a_idx'), models.Index(fields=['period_start'], name='seller_anal_period__b4efd4_idx')],
                'unique_together': {('seller_id', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('activity_type', models.CharField(max_length=50)),
                ('page', models.CharField(blank=True, max_length=255)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_activities',
                'indexes': [models.Index(fields=['user_id'], name='user_activi_user_id_260c6d_idx'), models.Index(fields=['activity_type'], name='user_activi_activit_534635_idx'), models.Index(fields=['timestamp'], name='user_activi_timesta_12eff7_idx')],
            },
        ),
    ]
